### ISSUE TITLE
Unable to integrate ServiceWorker.

### ISSUE THREAD

**Issue by karwank** [enten/angular-universal#14]
I have everything configured like in all other repositories on Angular 6. Browser throws an error:
<pre>
ERROR Error: Uncaught (in promise): TypeError: Failed to register a ServiceWorker: A bad HTTP response code (404) was received when fetching the script.
TypeError: Failed to register a ServiceWorker: A bad HTTP response code (404) was received when fetching the script
</pre>
The reason is that during `"build:prod": "ng run ng-universal:udk:production"` ngsw-worker.js file isn't created.

Does `ng-universal:udk` support it?

**Comment by enten** [comment]
Can you share a repository to investigate this issue?

**Comment by karwank** [comment]
Please look at: https://github.com/karwank/dealersite-ng-app

So I will describe what I have:

-  installed `"@angular/service-worker": "^6.1.1",`
- added to `app.browser.module.ts`:
    <pre>
    import { ServiceWorkerModule } from '@angular/service-worker';
    ServiceWorkerModule.register('ngsw-worker.js', { enabled: environment.production })</pre>
- created `src/manifest.json` file
- added `<link rel="manifest" href="manifest.json">` to `index.html`
- created `ngsw-config.json` file
- added to `angular.json` under `"build.options.assets"`:
  <pre>
  {
    "glob": "manifest.json",
    "input": "src",
    "output": "/"
  },
  </pre> 

I expected that after building code for production I will have `ngsw-worker.js` file in `dist/app/browser`.

**Comment by enten** [comment]
@karwank  
I started to investigate your issue.

Currently, I just reproduce the issue on the [current master branch](https://github.com/enten/angular-universal/tree/48385fd718c33700f09af4477a4823df36413a90):

* update dependencies with `npm install -D @angular/cli@6.2.0-beta.2 @angular-devkit/build-angular@0.7.0-rc.2 udk@0.3.15` ;
* [add service worker](https://angular.io/guide/service-worker-getting-started#adding-a-service-worker-to-your-project) with `ng add  @angular/pwa`.

When I run `ng run ng-universal:build:production`: the `ngsw-worker.js` is built.
**When I run `ng run ng-universal:udk:production` (or `npm run build:prod`): the `ngsw-worker.js` isn't built as you said.**

That behavior can be easily explained: the angular architect [browser builder enhances browser bundle when the `"serviceWorker"` option is `true`](https://github.com/angular/angular-cli/blob/8fd104036171190138058fe1668a72e38400a1c7/packages/angular_devkit/build_angular/src/browser/index.ts#L85).

Currently, the `udk` builder doesn't handle the `"serviceWorker"` option.

**I need to update udk to handle the `"serviceWork"` with [`augmentAppWithServiceWorker`](https://github.com/angular/angular-cli/blob/2cb4ac5f77a8574bcc1fa9b166c9816ab92b7ee5/packages/angular_devkit/build_angular/src/angular-cli-files/utilities/service-worker/index.ts#L111).**

**Comment by enten** [comment]
@karwank  

I published [udk@0.3.16](https://github.com/enten/udk/tree/v0.3.16) which [support `serviceWorker` option for brower target](https://github.com/enten/udk/commit/af274d67f145616e5fdca0d6aa46a091fbd3bf7d).

**Can you try to run commands below and give a feedback to tell us if your issue is fixed?**

```shell
npm install -D @angular/cli@6.2.0-beta.2 @angular-devkit/build-angular@0.7.0-rc.2 udk@0.3.16
npm run build:prod
node ./dist/app/server/main.js
# open http://localhost:4000 and check if service worker is registered
```

**Comment by karwank** [comment]
@enten 

It works for build:prod. ngsw-worker.js file has been created and worker is registered.

However this fix produces a new error for `npm run dev` (ng-udkc).

<pre>
deploy@hostname:~/ng-app$ npm run dev

> ng-universal@0.0.0 dev /home/deploy/ng-app
> ng-udkc

[udk] > bootstrap container
[udk] >> container up
[udk] unhandled rejection { reason: TypeError: this._workspace.getProjectArchitect is not a function
    at rxjs_1.forkJoin._workspace.listProjectNames.map.projectName (/home/deploy/ng-app/node_modules/@angular-devkit/architect/src/architect.js:71:66)
    at Array.map (<anonymous>)
    at MergeMapSubscriber.rxjs_1.forkJoin.pipe.operators_1.concatMap [as project] (/home/deploy/ng-app/node_modules/@angular-devkit/architect/src/architect.js:70:78)
    at MergeMapSubscriber._tryNext (/home/deploy/ng-app/node_modules/rxjs/internal/operators/mergeMap.js:65:27)
    at MergeMapSubscriber._next (/home/deploy/ng-app/node_modules/rxjs/internal/operators/mergeMap.js:55:18)
    at MergeMapSubscriber.Subscriber.next (/home/deploy/ng-app/node_modules/rxjs/internal/Subscriber.js:64:18)
    at ForkJoinSubscriber.notifyComplete (/home/deploy/ng-app/node_modules/rxjs/internal/observable/forkJoin.js:79:25)
    at InnerSubscriber._complete (/home/deploy/ng-app/node_modules/rxjs/internal/InnerSubscriber.js:32:21)
    at InnerSubscriber.Subscriber.complete (/home/deploy/ng-app/node_modules/rxjs/internal/Subscriber.js:76:18)
    at MapSubscriber.Subscriber._complete (/home/deploy/ng-app/node_modules/rxjs/internal/Subscriber.js:94:26)
    at MapSubscriber.Subscriber.complete (/home/deploy/ng-app/node_modules/rxjs/internal/Subscriber.js:76:18)
    at MapSubscriber.Subscriber._complete (/home/deploy/ng-app/node_modules/rxjs/internal/Subscriber.js:94:26)
    at MapSubscriber.Subscriber.complete (/home/deploy/ng-app/node_modules/rxjs/internal/Subscriber.js:76:18)
    at Observable.rxjs_1.Observable.obs [as _subscribe] (/home/deploy/ng-app/node_modules/@angular-devkit/core/node/host.js:173:21)
    at Observable._trySubscribe (/home/deploy/ng-app/node_modules/rxjs/internal/Observable.js:43:25)
    at Observable.subscribe (/home/deploy/ng-app/node_modules/rxjs/internal/Observable.js:29:22),
  promise: 
   Promise {
     <rejected> TypeError: this._workspace.getProjectArchitect is not a function
    at rxjs_1.forkJoin._workspace.listProjectNames.map.projectName (/home/deploy/ng-app/node_modules/@angular-devkit/architect/src/architect.js:71:66)
    at Array.map (<anonymous>)
    at MergeMapSubscriber.rxjs_1.forkJoin.pipe.operators_1.concatMap [as project] (/home/deploy/ng-app/node_modules/@angular-devkit/architect/src/architect.js:70:78)
    at MergeMapSubscriber._tryNext (/home/deploy/ng-app/node_modules/rxjs/internal/operators/mergeMap.js:65:27)
    at MergeMapSubscriber._next (/home/deploy/ng-app/node_modules/rxjs/internal/operators/mergeMap.js:55:18)
    at MergeMapSubscriber.Subscriber.next (/home/deploy/ng-app/node_modules/rxjs/internal/Subscriber.js:64:18)
    at ForkJoinSubscriber.notifyComplete (/home/deploy/ng-app/node_modules/rxjs/internal/observable/forkJoin.js:79:25)
    at InnerSubscriber._complete (/home/deploy/ng-app/node_modules/rxjs/internal/InnerSubscriber.js:32:21)
    at InnerSubscriber.Subscriber.complete (/home/deploy/ng-app/node_modules/rxjs/internal/Subscriber.js:76:18)
    at MapSubscriber.Subscriber._complete (/home/deploy/ng-app/node_modules/rxjs/internal/Subscriber.js:94:26)
    at MapSubscriber.Subscriber.complete (/home/deploy/ng-app/node_modules/rxjs/internal/Subscriber.js:76:18)
    at MapSubscriber.Subscriber._complete (/home/deploy/ng-app/node_modules/rxjs/internal/Subscriber.js:94:26)
    at MapSubscriber.Subscriber.complete (/home/deploy/ng-app/node_modules/rxjs/internal/Subscriber.js:76:18)
    at Observable.rxjs_1.Observable.obs [as _subscribe] (/home/deploy/ng-app/node_modules/@angular-devkit/core/node/host.js:173:21)
    at Observable._trySubscribe (/home/deploy/ng-app/node_modules/rxjs/internal/Observable.js:43:25)
    at Observable.subscribe (/home/deploy/ng-app/node_modules/rxjs/internal/Observable.js:29:22) } }
[udk] >> container down { event: 'exit', args: [ 0 ] }
TypeError: this._workspace.getProjectArchitect is not a function
    at rxjs_1.forkJoin._workspace.listProjectNames.map.projectName (/home/deploy/ng-app/node_modules/@angular-devkit/architect/src/architect.js:71:66)
    at Array.map (<anonymous>)
    at MergeMapSubscriber.rxjs_1.forkJoin.pipe.operators_1.concatMap [as project] (/home/deploy/ng-app/node_modules/@angular-devkit/architect/src/architect.js:70:78)
    at MergeMapSubscriber._tryNext (/home/deploy/ng-app/node_modules/rxjs/internal/operators/mergeMap.js:65:27)
    at MergeMapSubscriber._next (/home/deploy/ng-app/node_modules/rxjs/internal/operators/mergeMap.js:55:18)
    at MergeMapSubscriber.Subscriber.next (/home/deploy/ng-app/node_modules/rxjs/internal/Subscriber.js:64:18)
    at ForkJoinSubscriber.notifyComplete (/home/deploy/ng-app/node_modules/rxjs/internal/observable/forkJoin.js:79:25)
    at InnerSubscriber._complete (/home/deploy/ng-app/node_modules/rxjs/internal/InnerSubscriber.js:32:21)
    at InnerSubscriber.Subscriber.complete (/home/deploy/ng-app/node_modules/rxjs/internal/Subscriber.js:76:18)
    at MapSubscriber.Subscriber._complete (/home/deploy/ng-app/node_modules/rxjs/internal/Subscriber.js:94:26)
    at MapSubscriber.Subscriber.complete (/home/deploy/ng-app/node_modules/rxjs/internal/Subscriber.js:76:18)
    at MapSubscriber.Subscriber._complete (/home/deploy/ng-app/node_modules/rxjs/internal/Subscriber.js:94:26)
    at MapSubscriber.Subscriber.complete (/home/deploy/ng-app/node_modules/rxjs/internal/Subscriber.js:76:18)
    at Observable.rxjs_1.Observable.obs [as _subscribe] (/home/deploy/ng-app/node_modules/@angular-devkit/core/node/host.js:173:21)
    at Observable._trySubscribe (/home/deploy/ng-app/node_modules/rxjs/internal/Observable.js:43:25)
    at Observable.subscribe (/home/deploy/ng-app/node_modules/rxjs/internal/Observable.js:29:22)
</pre>

**Comment by enten** [comment]
@karwank  
Sorry, I made two mistakes:

* I forgot to [commit angular's dev container changes](https://github.com/enten/udk/commit/1f24e50a6c889695d36e5b2392b77b9a3eda9350) ;
* I updated to a wrong version of [`@angular-devkit/build-angular`](https://github.com/angular/angular-cli/tree/master/packages/angular_devkit/build_angular) (`0.7.0-rc.2` instead of `0.8.0-beta.0`).

I published [`udk@0.3.17`](https://github.com/enten/udk/tree/v0.3.17) which fix angular's dev container.

**Can you try to run commands below and give a feedback to tell us if your issue is fixed?**

```
npm install -D @angular/cli@6.2.0-beta.2 @angular-devkit/build-angular@0.8.0-beta.0 udk@0.3.17
npm run build:prod
node ./dist/app/server/main.js
# open http://localhost:4000 and check if service worker is registered
```

**Comment by karwank** [comment]
Everything works now. Thank You for your help and your work.

**Comment by enten** [comment]
@karwank Thanks you too for opening that issue with angular/pwa.

**Comment by dj-fiorex** [comment]
Hi all, i want to reopen this because i just started cloning this repo and do some tests, but the command 
`ng add @angular/pwa --project app`
doesn't work and give me an error 'Main file (undefined) not found'
Is there any problem with pwa?

#UPDATE#
trying to install Angular material with ng add @angular/material result in simil error: 
`Could not find the project main file inside of the workspace config (src)`

Thanks a lot

**Comment by enten** [comment]
@dj-fiorex 
Thanks for reporting issue.

I'm working on udk to support angular v10.

When it's done: I will try service worker feature and give you feedbacks.

**Comment by enten** [comment]
@dj-fiorex 
**Service worker still works with the repo.**

The commit with service worked added: https://github.com/enten/angular-universal/commit/39e837d736a6c9546f0d58113d9dd1d9544a7601

There are 2 ways to setup service worker: manually or dynamically with [schematic `@angular/pwa`](https://github.com/angular/angular-cli/tree/51849b684fb8b03db3c56e0f642de6e2dade6d09/packages/angular/pwa).

To setup manually: we should apply actions described in [Adding a service worker to your project](https://angular.io/guide/service-worker-getting-started#adding-a-service-worker-to-your-project) ourself:

> 1. Adds the `@angular/service-worker` package to your project.
> 2. Enables service worker build support in the CLI.
> 3. Imports and registers the service worker in the app module.
> 4. Updates the `index.html` file:
>     * Includes a link to add the `manifest.webmanifest` file.
>     * Adds meta tags for `theme-color`.
> 5. Installs icon files to support the installed Progressive Web App (PWA).
> 6. Creates the service worker configuration file called `ngsw-config.json`, which specifies the caching behaviors and other settings.

To setup dynamically with schematic `@angular/pwa`:
1. Open `angular.json` and rename target `app:build > app:universal` and target `app:browser > app:build`
```diff
--- a/angular.json
+++ b/angular.json
@@ -15,7 +15,7 @@
       "prefix": "app",
       "architect": {
-        "build": {
+        "universal": {
           "builder": "udk:udk-builder",
@@ -32,7 +32,7 @@
-        "browser": {
+        "build": {
           "builder": "@angular-devkit/build-angular:browser",
```
2. Run `ng add @angular/pwa --project app`
3. When schematic run complete: undo target renames `app:build > app.browser` and `app:universal > app:build`

Under the hood, schematic `@angular/pwa` expects to find browser build options in target `build`.
