### ISSUE TITLE
HRM on Angular Universal isn't working even installing the udk tools

### ISSUE THREAD

**Issue by IzioDev** [enten/angular-universal#18]
Hi,

I finally found out to install this package with this line indicated on the readme:
`npm install --save-dev udk webpack webpack-cli`

This installation were fine.
Then I added this dev script to my package.json:

```json
{
  "name": "ng-universal-demo",
  "version": "0.0.0",
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "https://github.com/angular/universal-starter.git"
  },
  "contributors": [
    "AngularClass <hello@angularclass.com>",
    "PatrickJS <patrick@angularclass.com>",
    "Jeff Whelpley <jeff@gethuman.com>",
    "Jeff Cross <crossj@google.com>",
    "Mark Pieszak <mpieszak84@gmail.com>",
    "Jason Jean <jasonjean1993@gmail.com>",
    "Fabian Wiles <fabian.wiles@gmail.com>"
  ],
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "lint": "ng lint ng-universal-demo",
    "dev": "ng-udkc",
    "build:client-and-server-bundles": "ng build --prod && ng run ng-universal-demo:server:production",
    "build:prerender": "npm run build:client-and-server-bundles && npm run compile:server && npm run generate:prerender",
    "build:ssr": "npm run build:client-and-server-bundles && npm run compile:server",
    "compile:server": "tsc -p server.tsconfig.json",
    "generate:prerender": "cd dist && node prerender",
    "serve:prerender": "cd dist/browser && http-server",
    "serve:ssr": "node dist/server"
  },
  "pre-commit": [],
  "private": true,
  "dependencies": {
    "@angular/animations": "^6.0.0",
    "@angular/common": "^6.0.0",
    "@angular/compiler": "^6.0.0",
    "@angular/core": "^6.0.0",
    "@angular/forms": "^6.0.0",
    "@angular/http": "^6.0.0",
    "@angular/platform-browser": "^6.0.0",
    "@angular/platform-browser-dynamic": "^6.0.0",
    "@angular/platform-server": "^6.0.0",
    "@angular/router": "^6.0.0",
    "@nguniversal/common": "^6.0.0",
    "@nguniversal/express-engine": "^6.0.0",
    "@nguniversal/module-map-ngfactory-loader": "^6.0.0",
    "core-js": "^2.4.1",
    "rxjs": "^6.2.2",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "0.6.0",
    "@angular/cli": "6.0.0",
    "@angular/compiler-cli": "^6.0.0",
    "@angular/language-service": "^6.0.0",
    "@types/node": "^8.0.30",
    "codelyzer": "^4.0.2",
    "express": "^4.15.2",
    "http-server": "^0.10.0",
    "pre-commit": "^1.2.2",
    "reflect-metadata": "^0.1.10",
    "ts-loader": "^4.2.0",
    "tslint": "^5.7.0",
    "typescript": "~2.7.2",
    "udk": "^0.3.17",
    "webpack": "^4.19.0",
    "webpack-cli": "^3.1.0"
  }
}

```

Then I tried to run : `npm run dev` and got this error:

```
/mnt/d/workSpace/Cours/Angular/universal-starter/node_modules/udk/angular/lib/devContainer.js:6
  async getBuilderContext(project) {
        ^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/mnt/d/workSpace/Cours/Angular/universal-starter/node_modules/udk/angular/bin/ng-udkc.js:10:22)
```

I then go to this file and TADA! an async identifier! Which is supposed to be working on Node version 9.11.1...

Any ideas on how to fix this?

```
izio@DESKTOP-JQ36KHQ:/mnt/d/workSpace/Cours/Angular/universal-starter$ npm -v
3.10.10
```
```
root@DESKTOP-JQ36KHQ:/mnt/d/workSpace/Cours/Angular/universal-starter# node -v
v9.11.1
```

**Comment by enten** [comment]
@izio38 
I tried with node `8.9.4` and that works well.

So node `9.11.0` should support async/await.

**Can you tried to run command below and give a feedback?**

```shell
node --harmony-async-await ./node_modules/udk/bin/udkc.js`
```
