### ISSUE TITLE
Could not find the implementation for builder udk:udk-builder

### ISSUE THREAD

**Issue by bokzor** [enten/angular-universal#30]
I just clone the master.
When a I try to launch the app with yarn start, here is the error I receive

```
Could not find the implementation for builder udk:udk-builder
Error: Could not find the implementation for builder udk:udk-builder
```

**Comment by enten** [comment]
I tried to clone, build and run the app:

* the app is successfully built - I don't hit your issue `Could not find the implementation for builder udk:udk-builder` ;
* the app failed to run due to `SyntaxError: Unexpected string` with `import 'zone.js/dist/zone-node';`.

@bokzor 
_Which versions do you use? Can you share `ng version` output?_

**@those who hit the syntax error**
We can temporarily fix that by bundle all dependencies in server bundle in `angular.json`.

**I will investigate why main server entry isn't transpile asap.**

```diff
        "server": {
          "builder": "@angular-devkit/build-angular:server",
          "options": {
            "outputPath": "dist/app/server",
            "main": "src/main.server.ts",
            "tsConfig": "src/tsconfig.server.json",
+           "bundleDependencies": "all"
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "outputHashing": "media"
            }
          }
        },
```
`"bundleDependencies": "all"`

```shell
$ git clone https://github.com/enten/angular-universal
$ cd angular-universal
$ npm install
$ npm run build
> angular-universal@0.0.0 build C:\Users\enten_s\code\angular-universal
> ng run angular:udk

 93% after chunk asset optimization SourceMapDevToolPlugin welcome-welcome-module.js generate SourceMaChild: browser
  Date: 2019-05-03T06:28:15.365Z
  Hash: 8805a72cbaf7225e7263
  Time: 8642ms
  chunk {main} main.js, main.js.map (main) 13.9 kB [initial] [rendered]
  chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 236 kB [initial] [rendered]
  chunk {runtime} runtime.js, runtime.js.map (runtime) 8.79 kB [entry] [rendered]
  chunk {styles} styles.js, styles.js.map (styles) 16.3 kB [initial] [rendered]
  chunk {vendor} vendor.js, vendor.js.map (vendor) 3.7 MB [initial] [rendered]
  chunk {welcome-welcome-module} welcome-welcome-module.js, welcome-welcome-module.js.map (welcome-welcome-module) 7.35 kB  [rendered]
Child: server
  Date: 2019-05-03T06:28:15.377Z
  Hash: c8b0b21fde40fc72f8f6
  Time: 3566ms
  chunk {main} main.js, main.js.map (main) 4.5 kB [entry] [rendered]

$ node dist\app\server\main.js
C:\Users\enten_s\code\angular-universal\src\main.server.ts:2
import 'zone.js/dist/zone-node';
       ^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected string
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
```

**Comment by bokzor** [comment]
8.0.0-rc.2

**Comment by enten** [comment]
@bokzor 
I found that angular architect api has changed:
https://blog.angular.io/introducing-cli-builders-d012d4489f1b

I need to update and publish a new version of udk-builder to consider the new architect API.

I still don't have internet: I can't work on this issue for the moment. I will notify when I will start to work on this.

**Comment by enten** [comment]
@bokzor 
I worked on [refactor udk:udk-builder](https://github.com/enten/udk/commit/20ebabc99f75677e23aa1995312a56750035a119) and release [udk v1.1.0-rc.0](https://github.com/enten/udk/tree/v1.1.0-rc.0) to support [angular/cli ^v8.0.0-beta.2](https://github.com/angular/angular-cli/tree/v8.0.0-beta.2).

**Can you try to install latest dev tools and try to run build and dev scripts? Are there any errors occurred?**

```shell
npm install -D udk@1.1.0-rc.0 @angular/cli@8.0.0-rc.4 @angular-devkit/build-angular@0.800.0-rc.4
# try universal build and run
ng run <project-name>:udk
node ./dist/app/server/main.js
# try dev container
./node_modules/.bin/ng-udkc
```
