### ISSUE TITLE
npm start has 'SyntaxError: Unexpected string' on main.server.ts

### ISSUE THREAD

**Issue by kaito3desuyo** [enten/angular-universal#32]
```
> angular-universal@0.0.0 start C:\Users\myname\Desktop\angular-universal-master
> node ./dist/app/server/main.js

C:\Users\myname\Desktop\angular-universal-master\src\main.server.ts:2
import 'zone.js/dist/zone-node';
       ^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected string
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-universal@0.0.0 start: `node ./dist/app/server/main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-universal@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\myname\AppData\Roaming\npm-cache\_logs\2019-05-22T00_27_06_496Z-debug.log
```

Windows 10 x64
node v10.15.3（by nodist v0.8.8）
npm 6.9.0

**Comment by enten** [comment]
I report this issue and it seems to be already fixed:
https://github.com/angular/angular-cli/issues/14333

**Comment by enten** [comment]
@kaito3desuyo 
Your issue is related to bug in previous beta versions of angular-devkit/build-angular.

**Can you try to install latest dev tools and try to run build and dev scripts? Are there any errors occurred?**

```shell
npm install -D udk@1.1.0-rc.0 @angular/cli@8.0.0-rc.4 @angular-devkit/build-angular@0.800.0-rc.4
# try universal build and run
ng run <project-name>:udk
node ./dist/app/server/main.js
# try dev container
./node_modules/.bin/ng-udkc
```

**Comment by kaito3desuyo** [comment]
@enten 
It worked after updating to the latest version.
Thank you your kindness.

**Comment by enten** [comment]
@kaito3desuyo 
You're welcome. It's a good news that udk-builder works again.

I will publish udk v1.1.0 when we are sure nothing breaks.
